align workspace_size to 64 MB to PyTorch
ROCm/hipBLASLt pull request #1212
Opened 2024-10-07 02:55 UTC by aazz44ss

PyTorch modify default workspace from 32MB to 64MB, align default workspace of hipblaslt-bench and tensilelite to PyTorch.

2024-10-07 03:03 UTC, AndySu12 approved these changes

2024-10-07 04:25 UTC, Serge45 approved these changes

2024-10-07 04:35 UTC, AndySu12 requested changes
This macro should be also modified. https://github.com/ROCm/hipBLASLt/blob/129026960bfb78952b00b196bbcfe451236bb1c7/tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp#L1513

2024-10-07 08:28 UTC, aazz44ss commented
> This macro should be also modified.
> 
> https://github.com/ROCm/hipBLASLt/blob/129026960bfb78952b00b196bbcfe451236bb1c7/tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp#L1513

No, this is checking workspace need to be less than 128MB.

2024-10-07 20:37 UTC, AlexBrownAMD requested changes
Lots of stream-k experiments require a larger workspace, and rocBLAS current default was increased to 128 MB as well. Can we keep the default at 128?

2024-10-09 16:22 UTC, AndySu12 approved these changes

2024-10-09 17:14 UTC, AlexBrownAMD approved these changes

2024-10-10 17:51 UTC, merged