Add initial optional stream-k libraries
ROCm/hipBLASLt pull request #1347
Opened 2024-11-15 05:12 UTC by AlexBrownAMD

Adding initial stream-k libraries that can be toggled on by setting the environment variable: TENSILE_SOLUTION_SELECTION_METHOD=2
These libraries include Bgemm BBS and BSS, Hgemm HHS and HSS, and Sgemm for gfx942, gfx942_80cu, and gfx942_228cu.
All libraries have passed rocBLAS validation testing, and links to performance analysis are available in chat.

2024-11-19 21:57 UTC, yoichiyoshida approved these changes

2024-11-20 02:54 UTC, KKyang approved these changes

2024-11-20 03:21 UTC, jichangjichang requested changes
please check CI errors

2024-11-21 08:14 UTC, jichangjichang commented
Please provide the library size diff and building time diff.

2024-12-04 15:06 UTC, AlexBrownAMD commented
Latest CI run passed.

Build time and build size increase by about 2%:

Develop branch build time: 51m56.576s
Develop branch build size: 22.1GiB

This PR build time: 53m18.001s
This PR build size: 22.6GiB

2024-12-05 00:58 UTC, jichangjichang approved these changes

2024-12-05 14:39 UTC, merged