Tune Aquavanjaram942X F8BS and F8B8BS TN for equality
ROCm/hipBLASLt pull request #1443
Opened 2024-12-12 15:45 UTC by pkamd

Added sizes for F8F8 and F8BF8 for TN configuration.
-Some have bias support.
-Ensured user provided commands pick these kernels.
-Ensured verification numbers are fine.

2024-12-12 15:46 UTC, smalekta approved these changes

2024-12-12 15:51 UTC, KKyang approved these changes

2024-12-20 16:22 UTC, babakpst approved these changes

2024-12-23 03:06 UTC, jichangjichang requested changes
Is it same with #1430 which has been in [release-staging/rocm-rel-6.4](https://github.com/ROCm/hipBLASLt/tree/release-staging/rocm-rel-6.4) ?

2024-12-23 14:52 UTC, pkamd commented
> Is it same with #1430 which has been in [release-staging/rocm-rel-6.4](https://github.com/ROCm/hipBLASLt/tree/release-staging/rocm-rel-6.4) ?

Yes. The changes are already present in the above mentioned branch.

2025-02-07 03:38 UTC, jichangjichang commented
close PR since there is no more staging build for release-staging/rocm-rel-6.4 branch

2025-02-07 03:38 UTC, closed without merging