Update NT BBS Equality yaml.
ROCm/hipBLASLt pull request #1498
Opened 2024-12-27 10:04 UTC by hcman2

Update NT BBS Equality yaml for some Large sizes.

2024-12-27 11:48 UTC, jichangjichang approved these changes, later dismissed

2024-12-27 15:11 UTC, AndySu12 approved these changes

2024-12-27 15:12 UTC, AndySu12 requested changes, later dismissed
The config should be SAV instead of SAB.

2024-12-30 07:10 UTC, AndySu12 approved these changes

2024-12-30 10:23 UTC, jichangjichang approved these changes

2025-01-02 01:59 UTC, merged