Doxyfile: enable warning as error message
ROCm/hipBLASLt pull request #176
Opened 2023-07-13 06:34 UTC by jichangjichang

2023-07-13 13:54 UTC, saadrahim requested changes
Please ensure the readthedocs CI is fixed. Please look at the readthedocs error messages.

```
Generating docs for file /h/home/docs/checkouts/readthedocs.org/user_builds/advanced-micro-devices-hipblaslt/checkouts/176/library/include/hipblaslt.h:463: error: End of list marker found without any preceding list items (warning treated as error, aborting now)
ome/docs/checkouts/readthedocs.org/user_builds/advanced-micro-devices-hipblaslt/checkouts/176/library/include/hipblaslt-ext.hpp...
```

2023-07-18 06:04 UTC, jichangjichang commented
> Please ensure the readthedocs CI is fixed. Please look at the readthedocs error messages.
> 
> ```
> Generating docs for file /h/home/docs/checkouts/readthedocs.org/user_builds/advanced-micro-devices-hipblaslt/checkouts/176/library/include/hipblaslt.h:463: error: End of list marker found without any preceding list items (warning treated as error, aborting now)
> ome/docs/checkouts/readthedocs.org/user_builds/advanced-micro-devices-hipblaslt/checkouts/176/library/include/hipblaslt-ext.hpp...
> ```
@saadrahim This warning is doxygen bug which has been solved in 1.9.2 (you can refer to https://github.com/doxygen/doxygen/issues/8163), but the doxygen of readthedocs for rocm is 1.8.13.
May I have your comment for this false alarm warning?
Do we still need to eanble WARN_AS_ERROR? If so, we may need to upgrade doxygen to 1.9.2 or later.

2023-07-21 21:29 UTC, saadrahim commented
> > Please ensure the readthedocs CI is fixed. Please look at the readthedocs error messages.
> > ```
> > Generating docs for file /h/home/docs/checkouts/readthedocs.org/user_builds/advanced-micro-devices-hipblaslt/checkouts/176/library/include/hipblaslt.h:463: error: End of list marker found without any preceding list items (warning treated as error, aborting now)
> > ome/docs/checkouts/readthedocs.org/user_builds/advanced-micro-devices-hipblaslt/checkouts/176/library/include/hipblaslt-ext.hpp...
> > ```
> 
> @saadrahim This warning is doxygen bug which has been solved in 1.9.2 (you can refer to [doxygen/doxygen#8163](https://github.com/doxygen/doxygen/issues/8163)), but the doxygen of readthedocs for rocm is 1.8.13. May I have your comment for this false alarm warning? Do we still need to eanble WARN_AS_ERROR? If so, we may need to upgrade doxygen to 1.9.2 or later.

@samjwu can you take a look at this issue?

2023-07-27 23:17 UTC, samjwu approved these changes

2023-07-27 23:17 UTC, merged