FP16/FP32 outputs with FP32 bias
ROCm/hipBLASLt pull request #193
Opened 2023-07-21 08:23 UTC by Jinp800125

FP16 inputs -> FP32 outputs with FP32 bias
FP16 inputs -> FP16 outputs with FP32 bias

2023-07-21 12:40 UTC, jichangjichang commented
It is better to update CI and doc along with this PR.

2023-07-22 08:17 UTC, KKyang requested changes

2023-07-22 08:17 UTC, KKyang commented on tensilelite/Tensile/Source/lib/source/ContractionSolution.cpp
> +            args.template append<uint32_t>("GSUSync", 0);
Don't put internal args in the middle of the user args
The format should be
Gemm:
user args + internal args 
Grouped gemm:
Wgtable + user args + internal args

2023-07-25 07:51 UTC, KKyang approved these changes

2023-07-26 06:33 UTC, jichangjichang approved these changes
LGTM

2023-07-26 10:09 UTC, Serge45 approved these changes

2023-07-26 15:39 UTC, merged