alpha vector sample
ROCm/hipBLASLt pull request #241
Opened 2023-08-08 11:25 UTC by Jinp800125

2023-08-08 13:36 UTC, KKyang requested changes

2023-08-08 13:36 UTC, KKyang commented on clients/samples/gemm/sample_hipblaslt_gemm_ext.cpp
Use a new sample instead of modifying the old one, e.g. ``samples/gemm_scaleAlphavec/sample_hipblaslt_gemm_scaleAlphavec_ext.cpp``

2023-08-08 18:14 UTC, Jinp800125 commented on clients/samples/gemm/sample_hipblaslt_gemm_ext.cpp
Sure. Before this already told the user this change just a temp will separate to another folder if needed.

2023-08-09 08:30 UTC, jichangjichang submitted a review, later dismissed
you should go legacy cublaslt api but not hipblaslt owned ext api for alpha vector sample.

2023-08-11 09:29 UTC, jichangjichang commented
> you should go legacy cublaslt api but not hipblaslt owned ext api for alpha vector sample.

I heared from yangwen that the ext sample request is from customer. So I removed the my request change.

2023-08-26 17:28 UTC, closed without merging