add AMax F32/F16 feature
ROCm/hipBLASLt pull request #337
Opened 2023-09-21 05:39 UTC by TonyYHsieh

add AbsMax feature to hipBlasLt with type F32 and F16

2023-09-26 12:01 UTC, KKyang requested changes
Add to sample or use bench instead.

2023-10-04 07:33 UTC, TonyYHsieh commented
> Add to sample or use bench instead.

remove sample first.
will develop ExtOp samples together.

2023-10-06 06:55 UTC, TonyYHsieh commented
> Add to sample or use bench instead.

add AMax sample

2023-10-06 07:51 UTC, jichangjichang commented
@TonyYHsieh  per our dicussion, the AMax's output scalar should support FP32.

2023-10-13 07:32 UTC, TonyYHsieh commented
> @TonyYHsieh per our dicussion, the AMax's output scalar should support FP32.

add support FP32 output scale for FP16/FP32 input

2023-10-13 07:48 UTC, Serge45 commented on tensilelite/Tensile/Ops/AMaxGenerator.py
> +        label = ti.Label("permute", f'permuge')
nitpick: typo here.

2023-10-13 07:53 UTC, TonyYHsieh commented on tensilelite/Tensile/Ops/AMaxGenerator.py
> +        label = ti.Label("permute", f'permuge')
fix typo

2023-10-16 01:44 UTC, KKyang approved these changes

2023-10-16 03:46 UTC, Serge45 approved these changes

2023-10-17 08:46 UTC, merged