Adopt hipDataType and deprecate hipblasltDatatype_t
ROCm/hipBLASLt pull request #423
Opened 2023-11-06 07:51 UTC by jichangjichang

2023-11-06 09:15 UTC, KKyang approved these changes

2023-11-06 16:13 UTC, jeffdaily requested changes
`hipblaslt_f8` type needs fnuz suffix.  

`Tensile::DataType::Float8` needs fnuz suffix.

2023-11-07 10:14 UTC, jichangjichang commented
> `hipblaslt_f8` type needs fnuz suffix.
> 
> `Tensile::DataType::Float8` needs fnuz suffix.

@jeffdaily I have revised hipblaslt_f8 and hipblaslt_bf8 with fnuz suffix.
For Tensile part, we won't modify it, since it is not user level code and hipblaslt's tensile current only support one f8 format  so far.
We would modify tensile part (hipblaslt owned) when another f8 format is implemented accordingly.

2023-11-09 14:07 UTC, jichangjichang commented
I have created another PR for [release/rocm-rel-6.0](https://github.com/ROCmSoftwarePlatform/hipBLASLt/tree/release/rocm-rel-6.0).
close this PR

2023-11-09 14:07 UTC, closed without merging