Fix GlobalSplitUCheckMinK not working properly when custom gsu is not set
ROCm/hipBLASLt pull request #468
Opened 2023-11-30 01:12 UTC by KKyang

2023-11-30 01:25 UTC, aazz44ss approved these changes

2023-11-30 03:38 UTC, Serge45 approved these changes

2023-11-30 12:52 UTC, jichangjichang requested changes
please correct formula per or discussion

2023-12-01 03:02 UTC, jichangjichang commented on tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp
>                          problem, stream, "prob", problem.boundSize(0), ">=", "sol", minK);
please sync the formula with operator()

2023-12-01 22:10 UTC, KKyang commented on tensilelite/Tensile/Source/lib/include/Tensile/ContractionProblemPredicates.hpp
>                          problem, stream, "prob", problem.boundSize(0), ">=", "sol", minK);
fixed

2023-12-05 02:13 UTC, jichangjichang approved these changes
lgtm

2023-12-05 02:13 UTC, merged