Add documentation cmake support
ROCm/hipBLASLt pull request #549
Opened 2024-01-10 14:29 UTC by matyas-streamhpc

2024-01-12 06:22 UTC, KKyang approved these changes

2024-01-15 16:26 UTC, jichangjichang approved these changes
LGTM

2024-01-16 02:03 UTC, KKyang requested changes
Please use rebase instead of merge, we can't help you fix the conflict because we don't have permission to access your branch.

2024-01-24 14:15 UTC, matyas-streamhpc commented
> Please use rebase instead of merge, we can't help you fix the conflict because we don't have permission to access your branch.

Thank you, it was some GitHub issue. Rebased.

2024-01-24 16:14 UTC, KKyang approved these changes

2024-03-09 02:32 UTC, merged