Update logic yaml
ROCm/hipBLASLt pull request #565
Opened 2024-01-17 09:29 UTC by hcman2

Update logic yaml of LSU4.

2024-01-17 09:30 UTC, KKyang approved these changes

2024-01-17 09:36 UTC, Jinp800125 approved these changes

2024-01-17 11:06 UTC, jichangjichang requested changes
gfx941 also need same kernels

2024-01-17 12:10 UTC, hcman2 commented
> gfx941 also need same kernels

updated

2024-01-17 13:06 UTC, jichangjichang approved these changes

2024-01-18 08:31 UTC, hcman2 commented
need to check the result again due to performance change on server.

2024-01-22 07:25 UTC, closed without merging