[Tensilelite] Enable Silu
ROCm/hipBLASLt pull request #584
Opened 2024-01-24 03:46 UTC by AndySu12

Silu(x) = x * Sigmoid(x)

2024-01-24 03:51 UTC, KKyang requested changes
1. Please use rebase instead of merge.
2. The two commits have the same message, please fix it.

2024-01-24 06:19 UTC, AndySu12 commented
@KKyang Done, thanks.

2024-01-29 08:13 UTC, KKyang requested changes

2024-01-29 08:13 UTC, KKyang commented on tensilelite/Tensile/Activation.py
> +    def getSiluModule(self, cDataType, vgprIn, vgprOut):
we already have sigmoid module, any reasons why can't call sigmoid here then add a mul x?
def getSiluModule(...):
    module.addModuleAsFlatItem(self.getSigmoidModule(...))
    module.add(VMulF32(...))

2024-01-29 08:16 UTC, AndySu12 commented on tensilelite/Tensile/Activation.py
> +    def getSiluModule(self, cDataType, vgprIn, vgprOut):
Good advice, I will use Sigmoid + mul. Initially I just use dedicated function, no further reason or consideration.

2024-01-29 09:08 UTC, AndySu12 commented on tensilelite/Tensile/Activation.py
> +    def getSiluModule(self, cDataType, vgprIn, vgprOut):
Done.

2024-01-30 01:43 UTC, KKyang approved these changes

2024-02-07 03:39 UTC, jichangjichang approved these changes
lgtm

2024-02-07 04:02 UTC, merged