Add frequency monitor to hipBLASlt - bench
ROCm/hipBLASLt pull request #781
Opened 2024-05-22 03:35 UTC by pkamd

This PR ports the frequency monitor present in rocBLAS to hipBLASlt that allows reporting frequency information while using hipBLASlt-bench. 

2 flags have been added to enable this feature - 

- ```HIPBLASLT_BENCH_FREQ=true``` to report minimum of the (average and median) XCD frequencies. 
- ```HIPBLASLT_BENCH_FREQ_ALL=true``` to report minimum of the (average and median) XCD frequencies.

Example usage 
- ```HIPBLASLT_BENCH_FREQ_ALL=true ./staging/hipblaslt-bench -f matmul -r s -m 4000 -n 4000 -k 4000 --lda 4000 --ldb 4000 --ldc 4000 --transA N --transB T -i 10000 -j 1000```
- ```HIPBLASLT_BENCH_FREQ=true ./staging/hipblaslt-bench -f matmul -r s -m 4000 -n 4000 -k 4000 --lda 4000 --ldb 4000 --ldc 4000 --transA N --transB T -i 10000 -j 1000```

2024-05-22 16:14 UTC, KKyang approved these changes

2024-05-27 20:11 UTC, babakpst approved these changes
@pkamd please merge the PR, once code owners approve the changes.

2024-05-28 03:17 UTC, KKyang requested changes
Can you use rebase instead of merge develop into this? If there is any reason to do that I'll change to approve again.

2024-05-28 03:25 UTC, KKyang approved these changes
nvm, I fixed it. Will merge/ Feel free to merge when tests pass.

2024-05-28 06:52 UTC, merged