Optimize GSU Workgroup Assignment
ROCm/hipBLASLt pull request #824
Opened 2024-06-12 14:27 UTC by ssuyuanchang

1. Workgroup order changed from interleaved to coalesced assignment.
2. Used "GlobalSplitUCoalesced" to enable in GSU kernel.

2024-06-13 05:31 UTC, KKyang approved these changes

2024-06-13 06:14 UTC, jichangjichang commented on tensilelite/Tensile/KernelWriterAssembly.py
> +        module.add(SCMovB32(dst=loopCounter, src=hex(0), comment="numIter=0 if gsuSimIdx != lastWg"))
typo gsuSimIdx

2024-06-18 13:41 UTC, ssuyuanchang commented on tensilelite/Tensile/KernelWriterAssembly.py
> +        module.add(SCMovB32(dst=loopCounter, src=hex(0), comment="numIter=0 if gsuSimIdx != lastWg"))
fixed

2024-06-19 03:51 UTC, ssuyuanchang commented
Local cl passed results:
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
------- generated xml file: /josh/hipBLASLt/tensilelite/python_tests.xml -------
[33m===== [32m51 passed[0m, [33m[1m18 skipped[0m, [33m[1m1 xfailed[0m, [33m[1m18 warnings[0m[33m in 21969.76s (6:06:09)[0m[33m =====[0m
py310: exit 0 (21970.07 seconds) /josh/hipBLASLt/tensilelite> py.test -v --basetemp=/josh/hipBLASLt/tensilelite/.tox/py310/tmp --junit-xml=/josh/hipBLASLt/tensilelite/python_tests.xml --junit-prefix=py310 --color=yes -n 4 --prebuilt-client=/josh/hipBLASLt/tensilelite/.tox/py310/client/0_Build/client/tensile_client Tensile/Tests -m common --capture=sys pid=20840
.pkg: _exit> python /usr/local/lib/python3.10/dist-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: exit None (0.00 seconds) /josh/hipBLASLt/tensilelite> python /usr/local/lib/python3.10/dist-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__ pid=12064
  py310: OK (22156.89=setup[21.09]+cmd[165.73,21970.07] seconds)
  congratulations :) (22156.98 seconds)

2024-06-19 03:56 UTC, hcman2 commented
> Local cl passed results: -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html ------- generated xml file: /josh/hipBLASLt/tensilelite/python_tests.xml ------- �[33m===== �[32m51 passed�[0m, �[33m�[1m18 skipped�[0m, �[33m�[1m1 xfailed�[0m, �[33m�[1m18 warnings�[0m�[33m in 21969.76s (6:06:09)�[0m�[33m =====�[0m py310: exit 0 (21970.07 seconds) /josh/hipBLASLt/tensilelite> py.test -v --basetemp=/josh/hipBLASLt/tensilelite/.tox/py310/tmp --junit-xml=/josh/hipBLASLt/tensilelite/python_tests.xml --junit-prefix=py310 --color=yes -n 4 --prebuilt-client=/josh/hipBLASLt/tensilelite/.tox/py310/client/0_Build/client/tensile_client Tensile/Tests -m common --capture=sys pid=20840 .pkg: _exit> python /usr/local/lib/python3.10/dist-packages/pyproject_api/_backend.py True setuptools.build_meta **legacy** .pkg: exit None (0.00 seconds) /josh/hipBLASLt/tensilelite> python /usr/local/lib/python3.10/dist-packages/pyproject_api/_backend.py True setuptools.build_meta **legacy** pid=12064 py310: OK (22156.89=setup[21.09]+cmd[165.73,21970.07] seconds) congratulations :) (22156.98 seconds)

2024-06-19 03:57 UTC, hcman2 commented
your ci pass only includes tensilelite. You need hipblaslt-test PASS

2024-06-19 04:22 UTC, jichangjichang requested changes, later dismissed
Please don't double size the tests of Tenisilelite. You should add your new arguments into some test which is focus on gsu

2024-06-19 05:03 UTC, ssuyuanchang commented
![image](https://github.com/ROCm/hipBLASLt/assets/16331341/fbda0d10-5f74-40ee-846f-eefc00c6e040)

2024-06-19 08:22 UTC, ssuyuanchang commented
> Please don't double size the tests of Tenisilelite. You should add your new arguments into some test which is focus on gsu

Fixed by adding only two test yaml for this feature

2024-06-19 10:54 UTC, jichangjichang commented
@ssuyuanchang  The different part between GSUC0 and GSUC1 is only in pre-loop global read address section and Tail loop section. Both of these sections are not in unroll-loop, which mean we can support these GSU0 and GSU1 in the same kernel. You can use a bit to distinguish which mode we want to use for each kernel launch.

@KKyang How do you think?

2024-06-20 01:36 UTC, ssuyuanchang commented
> @ssuyuanchang The different part between GSUC0 and GSUC1 is only in pre-loop global read address section and Tail loop section. Both of these sections are not in unroll-loop, which mean we can support these GSU0 and GSU1 in the same kernel. You can use a bit to distinguish which mode we want to use for each kernel launch.
> 
> @KKyang How do you think?

How about merging this PR first and then combine GSUC0 and GSUC1 into the same kernel in the future changes?

2024-06-20 01:47 UTC, hcman2 commented
> @ssuyuanchang The different part between GSUC0 and GSUC1 is only in pre-loop global read address section and Tail loop section. Both of these sections are not in unroll-loop, which mean we can support these GSU0 and GSU1 in the same kernel. You can use a bit to distinguish which mode we want to use for each kernel launch.
> 
> @KKyang How do you think?

sounds like we can move many of the parameters outside the main loop by using mode config?

2024-06-20 02:06 UTC, hcman2 approved these changes
OK if the CI error is fixed after rebase.

2024-06-20 02:07 UTC, merged