Add MAC F32 Instruction to Support Navi
ROCm/hipBLASLt pull request #876
Opened 2024-06-28 07:36 UTC by wenchuanchen

2024-06-28 07:49 UTC, KKyang requested changes
Adding instructions as texts are not allowed. I'll break the graph.

2024-06-28 07:50 UTC, hcman2 commented on clients/gtest/known_bugs.yaml
> +#- { function: matmul, a_type: f32_r, b_type: f32_r, c_type: f32_r, d_type: f32_r, compute_type: c_f32_r, scale_type: f32_r, known_bug_platforms: "gfx1100, gfx1101, gfx1102" }
Why not remove it?

2024-06-28 08:06 UTC, wenchuanchen commented
add know bugs, such as vector width, to reject list

2024-07-02 02:40 UTC, wenchuanchen commented on tensilelite/Tensile/TensileInstructions/Code.py
> +class Inst(Item):
remove

2024-07-02 02:41 UTC, wenchuanchen commented on tensilelite/Tensile/TensileInstructions/Macros.py
> +    # return module
remove

2024-07-02 02:41 UTC, wenchuanchen commented on tensilelite/Tensile/TensileInstructions/Macros.py
> +from .Code import Macro, Module, TextBlock
remove TextBlock

2024-07-08 05:29 UTC, KKyang requested changes

2024-07-08 05:29 UTC, KKyang commented on tensilelite/Tensile/TensileInstructions/Code.py
> +class Inst(Item):
This class is not allowed.

2024-07-08 05:29 UTC, KKyang commented on tensilelite/Tensile/BenchmarkProblems.py
> +
Remove the space

2024-07-08 05:29 UTC, KKyang commented on tensilelite/Tensile/TensileInstructions/Macros.py
> +def MacroMAC(kernel, tPA, tPB, innerUnroll, useMacro, defineMACs):
Why we need an extra wrapper for MAC?

2024-07-08 05:29 UTC, KKyang commented on tensilelite/Tensile/TensileCreateLibrary.py
> +
Remove extra space

2024-07-08 05:29 UTC, KKyang commented on tensilelite/Tensile/KernelWriterAssembly.py
> +      assert kernel["KernelLanguage"] == "Assembly"
Is the code here copied from KernelWriter.py? Can we use the same function?

2024-07-08 05:29 UTC, KKyang commented on tensilelite/Tensile/TensileInstructions/Macros.py
> +def MacroMAC(kernel, tPA, tPB, innerUnroll, useMacro, defineMACs):
I think we should move this to KernelWriterAssembly since it's not actually creating a Macro, more like calling a function in TensileLite instead of TensileInstructions.

2024-07-08 08:33 UTC, wenchuanchen commented on tensilelite/Tensile/KernelWriterAssembly.py
> +      assert kernel["KernelLanguage"] == "Assembly"
OK, I've merged KernelWriterAssembly's initKernel() into KernelWriter.

2024-07-08 08:34 UTC, wenchuanchen commented on tensilelite/Tensile/TensileInstructions/Macros.py
> +def MacroMAC(kernel, tPA, tPB, innerUnroll, useMacro, defineMACs):
Bring MacroMac into KernelWriterAssembly, and remove defineMACs.

2024-07-09 05:25 UTC, KKyang approved these changes

2024-07-10 02:55 UTC, cmingch approved these changes

2024-07-10 02:57 UTC, merged