Allows different CuCount Arch can share kernel object
ROCm/hipBLASLt pull request #978
Opened 2024-08-05 04:30 UTC by jichangjichang

with this, all tensile library and code object size is 16132M.
without this, all tensile library and code object size  is 16501M.

2024-08-05 06:49 UTC, KKyang requested changes
Not able to work cause Henry hardcoded the CU count into the asm kernels.

2024-08-05 07:05 UTC, jichangjichang commented
> Can't work cause Henry hardcoded the CU count into the asm kernels with fork parameters.

This PR only merged the code object for exact same kernels between 80 cu and 304cu. It won't impact the kernel selection design, which mean 80cu gfx942 can find 304 cu solution even without this PR.

2024-08-05 13:26 UTC, jichangjichang commented
need to wait until  ActivationFunCall is enabled for 80cu HHS/BBS.

2024-08-26 03:57 UTC, KKyang approved these changes

2025-06-20 18:16 UTC, jayhawk-commits commented
Closing the pull request in this repo. Please refer to the migrated pull request for updates.

2025-06-20 18:16 UTC, closed without merging